name: auth
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  get_it: ^7.2.0
  go_router: ^5.2.3
  hooks_riverpod: ^2.1.1
  intl_phone_field: ^3.1.0
  otp_text_field: ^1.1.3
  routes:
    path: ../routes
  styles:
    path: ../styles
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

import_sorter:
  comments: false

flutter:
  assets:
    - assets/
